
/**
 * AutostopowiczUsers generated by hbm2java
 */
public class AutostopowiczUsers  implements java.io.Serializable {


     private Integer autostopowiczId;
     private String autostopowiczName;
     private String autostopowiczLogin;
     private String autostopowiczPassword;
     private int autostopowiczRole;

    public AutostopowiczUsers() {
    }

    public AutostopowiczUsers(String autostopowiczName, String autostopowiczLogin, String autostopowiczPassword, int autostopowiczRole) {
       this.autostopowiczName = autostopowiczName;
       this.autostopowiczLogin = autostopowiczLogin;
       this.autostopowiczPassword = autostopowiczPassword;
       this.autostopowiczRole = autostopowiczRole;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAutostopowiczName() {
        return this.autostopowiczName;
    }
    
    public void setAutostopowiczName(String autostopowiczName) {
        this.autostopowiczName = autostopowiczName;
    }
    public String getAutostopowiczLogin() {
        return this.autostopowiczLogin;
    }
    
    public void setAutostopowiczLogin(String autostopowiczLogin) {
        this.autostopowiczLogin = autostopowiczLogin;
    }
    public String getAutostopowiczPassword() {
        return this.autostopowiczPassword;
    }
    
    public void setAutostopowiczPassword(String autostopowiczPassword) {
        this.autostopowiczPassword = autostopowiczPassword;
    }
    public int getAutostopowiczRole() {
        return this.autostopowiczRole;
    }
    
    public void setAutostopowiczRole(int autostopowiczRole) {
        this.autostopowiczRole = autostopowiczRole;
    }




}


