// default package
// Generated 2008-04-13 11:16:03 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private Integer idCountry;
     private String name;
     private Set drivesForIdCountryFrom = new HashSet(0);
     private Set users = new HashSet(0);
     private Set drivesForIdCountryTo = new HashSet(0);
     private Set cities = new HashSet(0);

    public Country() {
    }

	
    public Country(String name) {
        this.name = name;
    }
    public Country(String name, Set drivesForIdCountryFrom, Set users, Set drivesForIdCountryTo, Set cities) {
       this.name = name;
       this.drivesForIdCountryFrom = drivesForIdCountryFrom;
       this.users = users;
       this.drivesForIdCountryTo = drivesForIdCountryTo;
       this.cities = cities;
    }
   
    public Integer getIdCountry() {
        return this.idCountry;
    }
    
    public void setIdCountry(Integer idCountry) {
        this.idCountry = idCountry;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getDrivesForIdCountryFrom() {
        return this.drivesForIdCountryFrom;
    }
    
    public void setDrivesForIdCountryFrom(Set drivesForIdCountryFrom) {
        this.drivesForIdCountryFrom = drivesForIdCountryFrom;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getDrivesForIdCountryTo() {
        return this.drivesForIdCountryTo;
    }
    
    public void setDrivesForIdCountryTo(Set drivesForIdCountryTo) {
        this.drivesForIdCountryTo = drivesForIdCountryTo;
    }
    public Set getCities() {
        return this.cities;
    }
    
    public void setCities(Set cities) {
        this.cities = cities;
    }




}


