// default package
// Generated 2008-04-13 11:16:03 by Hibernate Tools 3.2.0.b11


import java.util.Date;

/**
 * Drive generated by hbm2java
 */
public class Drive  implements java.io.Serializable {


     private Integer idDrive;
     private User user;
     private Country countryByIdCountryFrom;
     private City cityByIdCityFrom;
     private City cityByIdCityTo;
     private Car car;
     private Country countryByIdCountryTo;
     private Date date;
     private int placeNumber;
     private boolean smoke;
     private float price;
     private String streetFrom;
     private String streetTo;

    public Drive() {
    }

    public Drive(User user, Country countryByIdCountryFrom, City cityByIdCityFrom, City cityByIdCityTo, Car car, Country countryByIdCountryTo, Date date, int placeNumber, boolean smoke, float price, String streetFrom, String streetTo) {
       this.user = user;
       this.countryByIdCountryFrom = countryByIdCountryFrom;
       this.cityByIdCityFrom = cityByIdCityFrom;
       this.cityByIdCityTo = cityByIdCityTo;
       this.car = car;
       this.countryByIdCountryTo = countryByIdCountryTo;
       this.date = date;
       this.placeNumber = placeNumber;
       this.smoke = smoke;
       this.price = price;
       this.streetFrom = streetFrom;
       this.streetTo = streetTo;
    }
   
    public Integer getIdDrive() {
        return this.idDrive;
    }
    
    public void setIdDrive(Integer idDrive) {
        this.idDrive = idDrive;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Country getCountryByIdCountryFrom() {
        return this.countryByIdCountryFrom;
    }
    
    public void setCountryByIdCountryFrom(Country countryByIdCountryFrom) {
        this.countryByIdCountryFrom = countryByIdCountryFrom;
    }
    public City getCityByIdCityFrom() {
        return this.cityByIdCityFrom;
    }
    
    public void setCityByIdCityFrom(City cityByIdCityFrom) {
        this.cityByIdCityFrom = cityByIdCityFrom;
    }
    public City getCityByIdCityTo() {
        return this.cityByIdCityTo;
    }
    
    public void setCityByIdCityTo(City cityByIdCityTo) {
        this.cityByIdCityTo = cityByIdCityTo;
    }
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }
    public Country getCountryByIdCountryTo() {
        return this.countryByIdCountryTo;
    }
    
    public void setCountryByIdCountryTo(Country countryByIdCountryTo) {
        this.countryByIdCountryTo = countryByIdCountryTo;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getPlaceNumber() {
        return this.placeNumber;
    }
    
    public void setPlaceNumber(int placeNumber) {
        this.placeNumber = placeNumber;
    }
    public boolean isSmoke() {
        return this.smoke;
    }
    
    public void setSmoke(boolean smoke) {
        this.smoke = smoke;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getStreetFrom() {
        return this.streetFrom;
    }
    
    public void setStreetFrom(String streetFrom) {
        this.streetFrom = streetFrom;
    }
    public String getStreetTo() {
        return this.streetTo;
    }
    
    public void setStreetTo(String streetTo) {
        this.streetTo = streetTo;
    }




}


