// default package
// Generated 2008-04-13 11:32:14 by Hibernate Tools 3.2.0.b11
package pl.com.autostopowicz.database.entities;

import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer idCity;
     private Country country;
     private String name;
     private Set users = new HashSet(0);
     private Set drivesForIdCityTo = new HashSet(0);
     private Set drivesForIdCityFrom = new HashSet(0);

    public City() {
    }

	
    public City(Country country, String name) {
        this.country = country;
        this.name = name;
    }
    public City(Country country, String name, Set users, Set drivesForIdCityTo, Set drivesForIdCityFrom) {
       this.country = country;
       this.name = name;
       this.users = users;
       this.drivesForIdCityTo = drivesForIdCityTo;
       this.drivesForIdCityFrom = drivesForIdCityFrom;
    }
   
    public Integer getIdCity() {
        return this.idCity;
    }
    
    public void setIdCity(Integer idCity) {
        this.idCity = idCity;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getDrivesForIdCityTo() {
        return this.drivesForIdCityTo;
    }
    
    public void setDrivesForIdCityTo(Set drivesForIdCityTo) {
        this.drivesForIdCityTo = drivesForIdCityTo;
    }
    public Set getDrivesForIdCityFrom() {
        return this.drivesForIdCityFrom;
    }
    
    public void setDrivesForIdCityFrom(Set drivesForIdCityFrom) {
        this.drivesForIdCityFrom = drivesForIdCityFrom;
    }




}


