package pl.com.autostopowicz.database.entities;
// Generated 2008-04-13 11:32:14 by Hibernate Tools 3.2.0.b11


import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer idGroup;
     private String name;
     private byte[] logo;
     private String description;
     private Set usergroups = new HashSet(0);

    public Group() {
    }

	
    public Group(String name) {
        this.name = name;
    }
    public Group(String name, byte[] logo, String description, Set usergroups) {
       this.name = name;
       this.logo = logo;
       this.description = description;
       this.usergroups = usergroups;
    }
   
    public Integer getIdGroup() {
        return this.idGroup;
    }
    
    public void setIdGroup(Integer idGroup) {
        this.idGroup = idGroup;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getUsergroups() {
        return this.usergroups;
    }
    
    public void setUsergroups(Set usergroups) {
        this.usergroups = usergroups;
    }




}


