package pl.com.autostopowicz.database.entities;
// Generated 2008-04-13 11:32:14 by Hibernate Tools 3.2.0.b11



/**
 * UsercarId generated by hbm2java
 */
public class UsercarId  implements java.io.Serializable {


     private int idUser;
     private int idCar;

    public UsercarId() {
    }

    public UsercarId(int idUser, int idCar) {
       this.idUser = idUser;
       this.idCar = idCar;
    }
   
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public int getIdCar() {
        return this.idCar;
    }
    
    public void setIdCar(int idCar) {
        this.idCar = idCar;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsercarId) ) return false;
		 UsercarId castOther = ( UsercarId ) other; 
         
		 return (this.getIdUser()==castOther.getIdUser())
 && (this.getIdCar()==castOther.getIdCar());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUser();
         result = 37 * result + this.getIdCar();
         return result;
   }   


}


