// default package
// Generated 2008-04-13 11:32:14 by Hibernate Tools 3.2.0.b11



/**
 * Usercar generated by hbm2java
 */
public class Usercar  implements java.io.Serializable {


     private UsercarId id;
     private User user;
     private Car car;
     private boolean owner;

    public Usercar() {
    }

    public Usercar(UsercarId id, User user, Car car, boolean owner) {
       this.id = id;
       this.user = user;
       this.car = car;
       this.owner = owner;
    }
   
    public UsercarId getId() {
        return this.id;
    }
    
    public void setId(UsercarId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }
    public boolean isOwner() {
        return this.owner;
    }
    
    public void setOwner(boolean owner) {
        this.owner = owner;
    }




}


