package pl.com.autostopowicz.entities;

// Generated 2008-04-13 11:32:14 by Hibernate Tools 3.2.0.b11

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;

/**
 * Drive generated by hbm2java
 */
@Entity
public class Drive implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -249128515422685284L;
	private Integer idDrive;
	private Integer idUser;
	private Integer idCountryFrom;
	private Integer idCountryTo;
	private Integer idCityFrom;
	private Integer idCityTo;
	private String streetFrom;
	private String streetTo;
	private Integer idCar;
	private Date date;
	private int placeNumber;
	private boolean smoke;
	private float price;

	private Car car;
	private User user;
	private Country countryFrom;
	private Country countryTo;
	private City cityFrom;
	private City cityTo;
	
	private Set<User> usersForDrive;
	

	public Drive() {
	}

	public Drive(Integer user, Integer countryByIdCountryFrom,
			Integer cityByIdCityFrom, Integer cityByIdCityTo, Integer car,
			Integer countryByIdCountryTo, Date date, int placeNumber,
			boolean smoke, float price, String streetFrom, String streetTo) {
		this.idUser = user;
		this.idCountryFrom = countryByIdCountryFrom;
		this.idCityFrom = cityByIdCityFrom;
		this.idCityTo = cityByIdCityTo;
		this.idCar = car;
		this.idCountryTo = countryByIdCountryTo;
		this.date = date;
		this.placeNumber = placeNumber;
		this.smoke = smoke;
		this.price = price;
		this.streetFrom = streetFrom;
		this.streetTo = streetTo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdDrive() {
		return idDrive;
	}

	public void setIdDrive(Integer idDrive) {
		this.idDrive = idDrive;
	}

	public Integer getIdCountryFrom() {
		return idCountryFrom;
	}

	public void setIdCountryFrom(Integer idCountryFrom) {
		this.idCountryFrom = idCountryFrom;
	}

	public Integer getIdCountryTo() {
		return idCountryTo;
	}

	public void setIdCountryTo(Integer idCountryTo) {
		this.idCountryTo = idCountryTo;
	}

	public Integer getIdCityFrom() {
		return idCityFrom;
	}

	public void setIdCityFrom(Integer idCityFrom) {
		this.idCityFrom = idCityFrom;
	}

	public Integer getIdCityTo() {
		return idCityTo;
	}

	public void setIdCityTo(Integer idCityTo) {
		this.idCityTo = idCityTo;
	}

	public String getStreetFrom() {
		return streetFrom;
	}

	public void setStreetFrom(String streetFrom) {
		this.streetFrom = streetFrom;
	}

	public String getStreetTo() {
		return streetTo;
	}

	public void setStreetTo(String streetTo) {
		this.streetTo = streetTo;
	}

	public Integer getIdCar() {
		return idCar;
	}

	public void setIdCar(Integer idCar) {
		this.idCar = idCar;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getPlaceNumber() {
		return placeNumber;
	}

	public void setPlaceNumber(int placeNumber) {
		this.placeNumber = placeNumber;
	}

	public boolean isSmoke() {
		return smoke;
	}

	public void setSmoke(boolean smoke) {
		this.smoke = smoke;
	}

	public float getPrice() {
		return price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public Integer getIdUser() {
		return idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@ManyToOne
	@JoinColumn(name = "idCar", insertable = false, updatable = false)
	// inverse = false
	public Car getCar() {
		return car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	@ManyToOne
	@JoinColumn(name = "idUser", insertable = false, updatable = false)
	// inverse = false
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne
	@JoinColumn(name = "idCountryFrom", insertable = false, updatable = false)
	// inverse = false
	public Country getCountryFrom() {
		return countryFrom;
	}

	public void setCountryFrom(Country countryFrom) {
		this.countryFrom = countryFrom;
	}

	@ManyToOne
	@JoinColumn(name = "idCountryTo", insertable = false, updatable = false)
	// inverse = false
	public Country getCountryTo() {
		return countryTo;
	}

	public void setCountryTo(Country countryTo) {
		this.countryTo = countryTo;
	}

	@ManyToOne
	@JoinColumn(name = "idCityFrom", insertable = false, updatable = false)
	// inverse = false
	public City getCityFrom() {
		return cityFrom;
	}

	public void setCityFrom(City cityFrom) {
		this.cityFrom = cityFrom;
	}

	@ManyToOne
	@JoinColumn(name = "idCityTo", insertable = false, updatable = false)
	// inverse = false
	public City getCityTo() {
		return cityTo;
	}

	public void setCityTo(City cityTo) {
		this.cityTo = cityTo;
	}
	@ManyToMany(
	        cascade = {CascadeType.PERSIST, CascadeType.MERGE},
	        mappedBy = "userDrives",
	        targetEntity = User.class
	    )

	public Set<User> getUsersForDrive() {
		return usersForDrive;
	}

	public void setUsersForDrive(Set<User> usersForDrive) {
		this.usersForDrive = usersForDrive;
	}
	
	
	/**
	 * Constructs a <code>String</code> with all attributes in name = value
	 * format.
	 * 
	 * @return a <code>String</code> representation of this object.
	 */
	public String toString() {
		final String TAB = "    ";

		String retValue = "";
		
		retValue = "Drive ( " + super.toString() + TAB + "idDrive = "
				+ this.idDrive + TAB + "idUser = " + this.idUser + TAB
				+ "idCountryFrom = " + this.idCountryFrom + TAB
				+ "idCountryTo = " + this.idCountryTo + TAB + "idCityFrom = "
				+ this.idCityFrom + TAB + "idCityTo = " + this.idCityTo + TAB
				+ "streetFrom = " + this.streetFrom + TAB + "streetTo = "
				+ this.streetTo + TAB + "idCar = " + this.idCar + TAB
				+ "date = " + this.date + TAB + "placeNumber = "
				+ this.placeNumber + TAB + "smoke = " + this.smoke + TAB
				+ "price = " + this.price + TAB;

		return retValue;
	}
	
	


}
