package pl.com.autostopowicz.entities;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
/**
 * User generated by hbm2java
 */
@Entity
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4008184770001248532L;
	private Integer idUser;
	private Country idCountry;
	private City idCity;
	private String login;
	private String password;
	private String email;
	private int role;
	private int rank;
	private String name;
	private String surname;
	private String address;
	private String phone;
	private String description;
	private int status;
	
	private Set<Drive> userDrives;
	

	public User() {
	}

	public User(String login, String password, String email, int role, int rank) {
		this.login = login;
		this.password = password;
		this.email = email;
		this.role = role;
		this.rank = rank;
	}

	public User(Country country, City city, String login, String password,
			String email, int role, int rank, String name, String surname,
			String address, String phone, String description, int status) {
		this.idCountry = country;
		this.idCity = city;
		this.login = login;
		this.password = password;
		this.email = email;
		this.role = role;
		this.rank = rank;
		this.name = name;
		this.surname = surname;
		this.address = address;
		this.phone = phone;
		this.description = description;
		this.status = status;

	}
	
	
	
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getRole() {
		return this.role;
	}

	public void setRole(int role) {
		this.role = role;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Country getIdCountry() {
		return idCountry;
	}

	public void setIdCountry(Country idCountry) {
		this.idCountry = idCountry;
	}

	public City getIdCity() {
		return idCity;
	}

	public void setIdCity(City idCity) {
		this.idCity = idCity;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}


	@ManyToMany
	@JoinTable(
		name = "userdrive",
	    joinColumns = @JoinColumn(name = "idUser"),
	    inverseJoinColumns = @JoinColumn(name = "idDrive"))
	public Set<Drive> getUserDrives() {
		return userDrives;
	}

	public void setUserDrives(Set<Drive> userDrives) {
		this.userDrives = userDrives;
	}

	/**
	 * Constructs a <code>String</code> with all attributes
	 * in name = value format.
	 *
	 * @return a <code>String</code> representation 
	 * of this object.
	 */
	public String toString()
	{
	    final String TAB = "    ";
	    
	    String retValue = "";
	    
	    retValue = "User ( "
	        + super.toString() + TAB
	        + "idUser = " + this.idUser + TAB
	        + "idCountry = " + this.idCountry + TAB
	        + "idCity = " + this.idCity + TAB
	        + "login = " + this.login + TAB
	        + "password = " + this.password + TAB
	        + "email = " + this.email + TAB
	        + "role = " + this.role + TAB
	        + "rank = " + this.rank + TAB
	        + "name = " + this.name + TAB
	        + "surname = " + this.surname + TAB
	        + "address = " + this.address + TAB
	        + "phone = " + this.phone + TAB
	        + "description = " + this.description + TAB
	        + "status = " + this.status + TAB
	        + " )";
	
	    return retValue;
	}

}
