// default package
// Generated 2008-04-13 11:32:14 by Hibernate Tools 3.2.0.b11
package pl.com.autostopowicz.entities;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * City generated by hbm2java
 */
@Entity
public class City implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8923938955672211389L;
	private Integer idCity;
	private Integer idCountry;
	private String name;

	public City() {
	}

	public City(Integer idCountry, String name) {

		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdCity() {
		return this.idCity;
	}

	public void setIdCity(Integer idCity) {
		this.idCity = idCity;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Constructs a <code>String</code> with all attributes in name = value
	 * format.
	 * 
	 * @return a <code>String</code> representation of this object.
	 */
	public String toString() {
		final String TAB = "    ";

		String retValue = "";

		retValue = "City ( " + super.toString() + TAB + "idCity = "
				+ this.idCity + TAB

				+ "name = " + this.name + TAB + " )";

		return retValue;
	}

	public Integer getIdCountry() {
		return idCountry;
	}

	public void setIdCountry(Integer idCountry) {
		this.idCountry = idCountry;
	}

}
