package pl.com.autostopowicz.entities;
// Generated 2008-04-13 11:32:14 by Hibernate Tools 3.2.0.b11


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Country generated by hbm2java
 */
@Entity
public class Country  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 3187439529146509781L;
	private Integer idCountry;
	private String name;

    public Country() {
    }

	
    public Country(String name) {
        this.name = name;
    }
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)

    public Integer getIdCountry() {
        return this.idCountry;
    }
    
    public void setIdCountry(Integer idCountry) {
        this.idCountry = idCountry;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


	/**
	 * Constructs a <code>String</code> with all attributes
	 * in name = value format.
	 *
	 * @return a <code>String</code> representation 
	 * of this object.
	 */
	public String toString()
	{
	    final String TAB = "    ";
	    
	    String retValue = "";
	    
	    retValue = "Country ( "
	        + super.toString() + TAB
	        + "idCountry = " + this.idCountry + TAB
	        + "name = " + this.name + TAB
	        + " )";
	
	    return retValue;
	}
  



}


